config/routes.rb
Rails.application.routes.draw do

  resources :formtemplates do
    resources :questions, except: [:index, :new] do
      member do
        get 'move_up'
        get 'move_down'
      end
    end
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'forms#index'

  resources :forms do
    member do
      get 'attempt'
      post 'attempting'
      get 'status'
      get 'results'
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :form_template
  has_many :answers, dependent: :destroy

  enum qns_type: { "Text Field": 1, "1 to 5 Collection": 2, "Text Area":3 }

  validates :label, presence: true, length: { maximum: 255 }
  validates :qns_type, presence: true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin
  before_action :set_question, only: [:edit, :destroy, :update, :move_up, :move_down]

  def edit
  end

  def move_up
    @formtemplate = FormTemplate.find(params[:formtemplate_id])

    if @question.qns_no > 1
      final_number = @question.qns_no - 1

      # Update question no of the one before
      @prev_question = @formtemplate.questions.find_by(qns_no: final_number)
      @prev_question.qns_no += 1
      @prev_question.save

      # Update question number
      @question.qns_no -= 1
      @question.save
    end

    respond_to do |format|
      format.js
    end
  end

  def move_down
    @formtemplate = FormTemplate.find(params[:formtemplate_id])

    if @question.qns_no < @formtemplate.questions.order('qns_no ASC').last.qns_no
      final_number = @question.qns_no + 1

      # Update question no of the one after
      @next_question = @formtemplate.questions.find_by(qns_no: final_number)
      @next_question.qns_no -= 1
      @next_question.save

      # Update own question no.
      @question.qns_no += 1
      @question.save
    end
    respond_to do |format|
      format.js
    end
  end

  def update
    @formtemplate = FormTemplate.find(params[:formtemplate_id])
    @question.update(question_params)
    @question.save
    redirect_to formtemplate_path(id: @formtemplate)
  end

  def create
    @formtemplate = FormTemplate.find(params[:formtemplate_id])
    @question = @formtemplate.questions.build(question_params)

    if @formtemplate.questions.count > 0
      last_question_no = @formtemplate.questions.order("qns_no ASC").last.qns_no
      @question.qns_no = last_question_no + 1
    else
      @question.qns_no = 1
    end

    if @question.save
      respond_to do |format|
        format.js
      end
    else
    end
  end

  def destroy
    @formtemplate = FormTemplate.find(params[:formtemplate_id])
    @question.destroy

    # Need to set the question number of the other questions.
    @questions = @formtemplate.questions.order('qns_no ASC')
    @questions.each_with_index do |question, index|
      question.qns_no = index + 1
      question.save
    end

    respond_to do |format|
      format.js
    end
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:label, :qns_type, :required, :qns_no)
  end

  def authenticate_admin
    if !current_user.is_admin
      flash[:notice] = "Only admin can view this page!"
      redirect_to root_path
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_list.html.erb
<h2>Question List</h2>
<% questions.order('qns_no ASC').each do |question| %>
  <% if !question.label.nil? %>
    <div class="panel panel-default">
      <div class="panel-body" style="display: flex; align-items: center;">

        <%# Button to move the questions number %>
        <div class="col-md-1" style="display: flex; flex-direction: column; align-items: center; ">
          <%= link_to '<span class="glyphicon glyphicon-chevron-up btn btn-default" aria-hidden="true"></span>'.html_safe, move_up_formtemplate_question_path(formtemplate_id: question.form_template, id: question), remote: true %><br />
          <%= link_to '<span class="glyphicon glyphicon-chevron-down btn btn-default" aria-hidden="true"></span>'.html_safe, move_down_formtemplate_question_path(formtemplate_id: question.form_template, id: question), remote: true %>
        </div>

        <%# Main Queston Details %>
        <div class="col-md-9">
          <div class="row">
            <div class="col-md-2">
              Q. <%= question.qns_no %>
            </div>
            <div class="col-md-8">
              <%= question.label %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-2">
              Type:
            </div>
            <div class="col-md-3">
              <%= question.qns_type %>
            </div>
            <div class="col-md-2">
              Required:
            </div>
            <div class="col-md-3">
              <%= question.required %>
            </div>
          </div>
        </div>

        <%# Edit and Delete buttons %>
        <div class="col-md-2">
          <%= link_to 'Edit', edit_formtemplate_question_path(formtemplate_id: question.form_template, id: question), class: "btn btn-primary" %>
          <%= link_to 'Delete', formtemplate_question_path(formtemplate_id: question.form_template, id: question), method: :delete, remote: true, class: "btn btn-primary", data: { confirm: "Are you sure you want to delete this question?"} %>
        </div>

        <!--
        <table class="table">
          <tr>
            <td span="2">Title: <%= question.label %></td>
          </tr>
          <tr>
            <td>Question Type: <%= question.qns_type %></td>
            <td>
            <%= link_to 'Edit', edit_formtemplate_question_path(formtemplate_id: question.form_template, id: question) %>
            <%= link_to 'Delete', formtemplate_question_path(formtemplate_id: question.form_template, id: question), method: :delete, remote: true %>
            </td>
          </tr>
        </table>
        -->
      </div>
    </div>
  <% end %>
<% end %>

app/views/questions/_new.html.erb
<h1>Questions</h1>
<% @question = formtemplate.questions.build %>
<%= simple_form_for @question, url: formtemplate_questions_path(formtemplate.id), remote: true do |f| %>
  <%= f.input :label %>
  <%= f.input :qns_type, collection: ["Text Field", "1 to 5 Collection", "Text Area"], selected: "Text Field" %>
  <%= f.input :required, collection: [["True", true], ["False", false]] %>
  <%= f.button :submit %>
<% end %>

app/views/questions/create.js.erb
$('#newquestion').html("<%= j render partial: 'questions/new', locals: { formtemplate: @formtemplate } %>")
$('#questionlist').html("<%= j render partial: 'questions/list', locals: { questions: @formtemplate.questions } %>")

app/views/questions/destroy.js.erb
$('#newquestion').html("<%= j render partial: 'questions/new', locals: { formtemplate: @formtemplate } %>")
$('#questionlist').html("<%= j render partial: 'questions/list', locals: { questions: @formtemplate.questions } %>")

app/views/questions/edit.html.erb
<h1>Question Edit</h1>
<%= simple_form_for @question,
  url: formtemplate_question_path(formtemplate_id: params[:formtemplate_id],
                                  id: @question.id) do |f| %>
  <%= f.input :label %>
  <%= f.input :qns_type, collection: ["Text Field", "1 to 5 Collection", "Text Area"], selected: "Text Field" %>
  <%= f.input :required, collection: [["True", true], ["False", false]] %>
  <%= f.button :submit %>
<% end %>

app/views/questions/move_down.js.erb
$('#questionlist').html("<%= j render partial: 'questions/list', locals: { questions: @formtemplate.questions } %>")

app/views/questions/move_up.js.erb
$('#questionlist').html("<%= j render partial: 'questions/list', locals: { questions: @formtemplate.questions } %>")

app/views/questions/update.html.erb
<h1>Questions#update</h1>
<p>Find me in app/views/questions/update.html.erb</p>