config/routes.rb
Rails.application.routes.draw do

  resources :formtemplates do
    resources :questions, except: [:index, :new] do
      member do
        get 'move_up'
        get 'move_down'
      end
    end
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'forms#index'

  resources :forms do
    member do
      get 'attempt'
      post 'attempting'
      get 'status'
      get 'results'
    end
  end
end

app/models/form_template.rb
class FormTemplate < ApplicationRecord
  belongs_to :user
  has_many :forms, dependent: :destroy
  has_many :questions, dependent: :destroy

  validates :user, presence: true
  validates :title, presence: true, length: { maximum: 255 }
  validates :description, length: { maximum: 1000 }
end

app/controllers/formtemplates_controller.rb
class FormtemplatesController < ApplicationController

  before_action :authenticate_user!
  before_action :authenticate_admin
  before_action :set_formtemplate, only: [:show, :edit, :update, :destroy]

  def index
    @formtemplates = FormTemplate.all.order(:id)
  end

  def show
    @questions = @formtemplate.questions
  end

  def new
    @formtemplate = FormTemplate.new
  end

  def create
    @formtemplate = FormTemplate.new(formtemplate_params)
    @formtemplate.user = current_user
    if @formtemplate.save
      redirect_to edit_formtemplate_path(@formtemplate)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @formtemplate.update(formtemplate_params)
    @formtemplate.save
    redirect_to edit_formtemplate_path(@formtemplate)
  end

  def destroy
    @formtemplate.destroy
    redirect_to formtemplates_path
  end

  private

  def set_formtemplate
    @formtemplate = FormTemplate.find(params[:id])
  end

  def authenticate_admin
    if !current_user.is_admin
      flash[:notice] = "Only admin can view this page!"
      redirect_to root_path
    end
  end

  def formtemplate_params
    params.require(:form_template).permit(:title, :description)
  end
end

app/helpers/formtemplates_helper.rb
module FormtemplatesHelper
end

app/views/formtemplates/_form.html.erb
<%= simple_form_for @formtemplate, url: formtemplates_path do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/formtemplates/edit.html.erb
<h1>Edit Form Template</h1>
<%= simple_form_for @formtemplate, url: formtemplate_path do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

<div id="newquestion">
  <%= render partial: 'questions/new', locals: { formtemplate: @formtemplate } %>
</div>
<div id="questionlist">
  <%= render partial: 'questions/list', locals: { questions: @formtemplate.questions } %>
</div>

app/views/formtemplates/index.html.erb
<h1>Form Templates List</h1>
<div style="padding: 0 0 30px 0; display: flex; justify-content: flex-end">
  <%= link_to "New Form Template", new_formtemplate_path, class: "btn btn-primary" %>
</div>
<table class="table">
  <tr>
    <th>
      Form Template ID
    </th>
    <th>
      Template Title
    </th>
    <th>
      Description
    </th>
    <th>
      Author
    </th>
    <th>
      Actions
    </th>
  </tr>
  <% @formtemplates.each do |formtemplate| %>
    <tr>
      <td>
        <%= formtemplate.id %>
      </td>
      <td>
        <%= link_to formtemplate.title, formtemplate_path(formtemplate) %>
      </td>
      <td>
        <%= formtemplate.description %>
      </td>
      <td>
        <%= formtemplate.user.first_name %>
      </td>
      <td>
        <%= link_to 'Edit', edit_formtemplate_path(formtemplate) %>
        <%= link_to 'Delete', formtemplate_path(formtemplate), method: :delete, data: {confirm: "Are you sure? This will delete all Forms, Questions, and Answers linked to this template. Linked Resources: Forms: #{formtemplate.forms.count}, Questions: #{formtemplate.questions.count}".html_safe}  %>
      </td>
    </tr>
  <% end %>
</table>

app/views/formtemplates/new.html.erb
<h1>Create new Formtemplate</h1>
<%= render 'form' %>

app/views/formtemplates/show.html.erb
<h1>Formtemplates</h1>

<div class="panel panel-default">
  <table class="table">
    <tr>
      <td>Title</td>
      <td><%= @formtemplate.title %></td>
    </tr>
    <tr>
      <td>Description</td>
      <td><%= @formtemplate.description %></td>
    </tr>
    <tr>
      <td>Author</td>
      <td><%= @formtemplate.user.first_name %></td>
    </tr>

  </table>
</div>

<div>
  <%= link_to 'Edit FormTemplate or Add Questions', edit_formtemplate_path(@formtemplate), class: "btn btn-primary" %>
  <%= link_to 'Create Form with Template', new_form_path(form_template: @formtemplate), class: "btn btn-primary" %>
</div>
<br />

<div id="questionlist">
  <%= render partial: 'questions/list', locals: { questions: @formtemplate.questions } %>
</div>