config/routes.rb
Rails.application.routes.draw do

  resources :formtemplates do
    resources :questions, except: [:index, :new] do
      member do
        get 'move_up'
        get 'move_down'
      end
    end
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'forms#index'

  resources :forms do
    member do
      get 'attempt'
      post 'attempting'
      get 'status'
      get 'results'
    end
  end
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController

  before_action :authenticate_user!
  before_action :authenticate_admin, except: [:index, :attempt, :attempting]
  before_action :setup_form, only: [:show, :attempt, :attempting, :status, :results, :destroy, :edit, :update]
  before_action :setup_questions, only: [:show, :results]

  def new
    @form = current_user.forms.build
  end

  def show
  end

  def create
    @form = current_user.forms.build(form_params)
    if @form.save
      redirect_to form_path(@form)
    else
      render :new
    end
  end

  def destroy
    @form.destroy
    redirect_to forms_path
  end

  def update
    @form.update(form_params)
    @form.save
    redirect_to form_path(@form)
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def index
    @forms = Form.all.order('created_at DESC')
  end

  def attempt
  end

  def attempting
    #array = [:q1, :q2, :q3, :q4, :q5, :q6, :q7, :q8, :q9, :q10]
    save_success = true
    @invalid_fields = []
    @values_cache = []
    @form.questions.order('qns_no ASC').each_with_index do |question, index|
      params_symbol = ('q'+(index+1).to_s).to_sym
      @answer = question.answers.build(content: params[:form][params_symbol], form: @form)
      @answer.user = current_user
      @values_cache << @answer.content
      if (question.required && (@answer.content.nil? || @answer.content.empty?))
        flash[:notice] = "Please fill in required fields!"
        save_success = false
        @invalid_fields << question.id
      else
        @answer.save
      end
    end

    if save_success
      @log = @form.logs.build(user: current_user)
      @log.save

      redirect_to forms_path
    else
      @answers = Answer.where(form: @form, question: @form.questions, user: current_user)
      @answers.each do |answer|
        answer.destroy
      end
      redirect_to attempt_form_path(values_cache: @values_cache, invalid_fields: @invalid_fields)
    end
  end

  def status
    @logs = @form.logs
    @users = User.all
    respond_to do |format|
      format.js
    end
  end

  def results
    respond_to do |format|
      format.js
    end
  end

  private

  def setup_form
    @form = Form.find(params[:id])
  end

  def setup_questions
    @questions = @form.questions
  end

  def attempting_params
  end

  def form_params
    params.require(:form).permit(:form_template_id, :form_date, :title, :description)
  end

  def authenticate_admin
    if !current_user.is_admin
      flash[:notice] = "Only admin can view this page!"
      redirect_to root_path
    end
  end
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/views/forms/_edit.html.erb
<% @heading = "Edit" %>
<%= render 'forms/header' %>
<%= simple_form_for @form do |f| %>
  <% if params[:form_template].nil? %>
    <%= f.association :form_template, collection: FormTemplate.all %>
  <% else %>
    <%= f.association :form_template, collection: FormTemplate.all, selected: params[:form_template] %>
  <% end %>
  <%= f.input :form_date, as: :date %>
  <%= f.input :title %>
  <%= f.input :description, as: :text %>
  <%= f.button :submit %>
<% end %>
<div style="display: flex; justify-content: flex-end;">
<%= link_to 'Delete this form', form_path(@form), method: :delete, data: { confirm: "Are you sure you want to delete this form?" }, class: "btn btn-danger"%>
</div>

app/views/forms/_header.html.erb
<h2><%= @heading %></h2>
<div class="panel panel-default">
  <div class="panel-heading">
  <h3><%= @form.title %></h3>
  </div>
  <div class="panel-body">
    <%= @form.description %>
  </div>
</div>

app/views/forms/_nav.html.erb
<nav class="nav navbar-default">
  <ul class="nav navbar-nav">
    <li>
      <%= link_to  "Current Form ID: #{@form.id}", results_form_path(@form), remote: true %>
    </li>
    <li>
      <%= link_to 'Edit', edit_form_path(@form), remote: true %>
    </li>
    <li>
      <%= link_to 'Status', status_form_path(@form), remote: true %>
    </li>
    <li>
      <%= link_to 'Edit Template/Add Questions', edit_formtemplate_path(@form.form_template) %>
    </li>
    <li>
      <%= link_to 'Back to all Forms', forms_path %>
    </li>
  </ul>
</nav>

app/views/forms/_results.html.erb
<% @heading = "Results" %>
<%= render 'forms/header' %>
<% @questions.each do |question| %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <div class="row">
        <div class="col-md-10">
          <div class="row">
            <div class="col-md-1">
              <h4><b>Q. <%= question.qns_no %></b></h4>
            </div>
            <div class="col-md-8">
              <b><%= question.label %></b>
            </div>
          </div>
          <div class="row">
            <div class="col-md-1">
            </div>
            <div class="col-md-1">
              Type:
            </div>
            <div class="col-md-3">
              <%= question.qns_type %>
            </div>
            <div class="col-md-2">
              Required:
            </div>
            <div class="col-md-2">
              <%= question.required %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="panel-body">

      <%# Graph if number %>
      <% if question.qns_type == "1 to 5 Collection" %>
        <%= column_chart question.answers.where(form: @form).group(:content).count %>
      <% end %>
      <h4> Total Answers: <%= question.answers.where(form: @form).count %></h4>
      <%# Raw data %>
      <table class="table table-bordered">
        <tr>
          <th class="col-xs-1">
            Index
          </th>
          <th class="col-xs-3 col-md-2">
            User
          </th>
          <th>
            Content
          </th>
        </tr>
        <% question.answers.where(form: @form).each_with_index do |answer, index| %>
          <tr>
            <td style="padding: 5px"><%= index+1 %></td>
            <td style="padding: 5px"><%= answer.user.username %></td>
            <td style="padding: 5px"><%= answer.content %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
<% end %>

app/views/forms/_status.html.erb
<% @heading = "Status" %>
<%= render 'forms/header' %>

<h2>Users that have attempted the form</h2>
<div class="panel panel-default">
  <table class="table">
    <tr>
      <th class="col-xs-3">
        Username
      </th>
      <th>
        Name
      </th>
      <th>
        Date Attempted
      </th>
    </tr>
    <% @logs.each do |log| %>
      <% @user = log.user %>
      <tr>
        <td>
          <%= @user.username %>
        </td>
        <td>
          <%= @user.first_name %> <%= @user.last_name %>
        </td>
        <td>
          <%= log.created_at %>
        </td>
      </tr>
    <% end %>
  </table>
</div>
<h2>Yet to attempt..</h2>
<div class="panel panel-default">
  <table class="table">
    <tr>
      <th class="col-xs-3">
        User
      </th>
      <th>
        Name
      </th>
    </tr>
    <% @users.each do |user| %>
      <% if !@logs.exists?(user: user.id) && user != @form.user %>
        <tr>
          <td>
            <%= user.username %>
          </td>
          <td>
            <%= user.first_name %> <%= user.last_name %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </table>
</div>

app/views/forms/attempt.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1><%= @form.title %></h1>
    <%= @form.description %>
  </div>


  <% if flash[:notice] %>
    <div class="alert alert-warning" role="alert">
      <%= flash[:notice] %>
      <% if !params[:invalid_fields].nil? %>
        Required:
        <% params[:invalid_fields].each do |qns_id| %>
           Q<%= Question.find(qns_id).qns_no %>
           <%= qns_id == params[:invalid_fields].last ? "" : "," %>
        <% end %>
      <% end %>
    </div>
  <% end %>

  <div class="panel-body" style="padding: 30px">

    <%= simple_form_for @form, url: attempting_form_path, method: :post do |f| %>

      <% @form.questions.order('qns_no ASC').each_with_index do |question, index| %>
        <% params_symbol = ('q'+(index+1).to_s).to_sym %>
        <div class="form-inputs" style="padding: 30px 0">
          <h4>
            <%= question.label %>
          </h4>
          <% case question.qns_type_before_type_cast %>
          <% when 1 %>
            <%= f.input params_symbol, required: question.required ? true : false,
              input_html: { value: (params[:values_cache].nil? ? "" : params[:values_cache][index]) } %>
          <% when 2 %>
            <%= f.input params_symbol, collection: (1..5), include_blank: "(Select one)", selected: (params[:values_cache].nil? ? nil : params[:values_cache][index]), required: question.required ? true : false %>
          <% when 3 %>
            <%= f.input params_symbol, as: :text, required: question.required ? true : false,
              input_html: { value: (params[:values_cache].nil? ? "" : params[:values_cache][index]) } %>
          <% end %>
        </div>
      <% end %>
      <div class="actions">
        <%= f.button :submit %>
      </div>
    <% end %>

  </div>
</div>

app/views/forms/edit.js.erb
$('#show_content').html("<%= j render partial: 'forms/edit' %>");

app/views/forms/index.html.erb
<% if flash[:notice] %>
  <div class="alert alert-warning" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>

<h1>Forms index</h1>
<% if current_user.is_admin %>
  <div style="padding: 0 0 30px 0; display: flex; justify-content: flex-end">
    <%= link_to 'New Form', new_form_path, class: "btn btn-primary"%>
  </div>
<% end %>

<table class="table">
  <tr>
    <th>Title and Description</th>
    <th>Author</th>
    <th>Date</th>
    <% if current_user.is_admin %>
      <th>Template Title</th>
      <th>Attempts</th>
    <% end %>
    <th>Status</th>
    <th>Link</th>
  </tr>

  <% @forms.each do |form| %>
    <tr>
      <td>
        <% if current_user == form.user || current_user.is_admin == true %>
        <b><%= link_to form.title, form_path(form) %></b>
        <% else %>
        <b><%= form.title %></b>
        <% end %><br />
        <%= form.description %>
      </td>
      <td>
        <%= form.user.first_name %>
      </td>
      <td>
        <%= form.form_date %>
      </td>
      <% if current_user.is_admin %>
        <td>
          <%= form.form_template.title %>
        </td>
        <td>
          <% if form.questions.present? %>
            <%= form.questions.first.answers.where(form: form).count %> / <%= User.count - 1 %>
          <% else %>
            No Questions to do!
          <%  end %>
        </td>
      <% end %>
      <!-- Check log model -->
      <% if form.logs.exists?(user: current_user) %>
        <td>
          <span class="glyphicon glyphicon-ok"></span>
        </td>
        <td>
          Done
        </td>
      <% else %>
        <td>
          <span class="glyphicon glyphicon-remove"></span>
        </td>
        <td>
          <!-- Click to attempt or already Done -->
          <%= link_to 'Attempt Now', attempt_form_path(form) %>
        </td>
      <% end %>
      </td>
    <tr>
  <% end %>
</table>

app/views/forms/new.html.erb
<h1>New Form</h1>

<%= simple_form_for @form do |f| %>
  <% if params[:form_template].nil? %>
    <%= f.association :form_template, collection: FormTemplate.all %>
    <%= f.input :form_date, as: :date %>
    <%= f.input :title %>
    <%= f.input :description, as: :text %>
  <% else %>
    <% @formtemplate = FormTemplate.find(params[:form_template]) %>
    <%= f.association :form_template, collection: FormTemplate.all, selected: params[:form_template] %>
    <%= f.input :form_date, as: :date %>
    <%= f.input :title, input_html: { value: @formtemplate.title.gsub(/template[s]?$/i, "") } %>
    <%= f.input :description, as: :text, input_html: { value: @formtemplate.description } %>
  <% end %>
  <%= f.button :submit %>
<% end %>

app/views/forms/results.js.erb
$('#show_content').html("<%= j render partial: 'forms/results' %>");

app/views/forms/show.html.erb
<% if current_user == @form.user || current_user.is_admin == true %>
<%= render 'forms/nav' %>
<div id="show_content">
  <%= render partial: 'forms/results' %>
</div>

<% else %>
You are not allowed!
<% end %>

app/views/forms/status.js.erb
$('#show_content').html("<%= j render partial: 'forms/status' %>");