config/routes.rb
Rails.application.routes.draw do

  resources :formtemplates do
    resources :questions, except: [:index, :new] do
      member do
        get 'move_up'
        get 'move_down'
      end
    end
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'forms#index'

  resources :forms do
    member do
      get 'attempt'
      post 'attempting'
      get 'status'
      get 'results'
    end
  end
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse navbar-static-top">
  <div class="container-fluid">
    <div class="navbar-header">
    </div>

    <ul class="nav navbar-nav navbar-left">
      <li><%= link_to 'Home', forms_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to 'Forms', forms_path %></li>
        <% if current_user.is_admin %>
          <li><%= link_to 'Form Templates', formtemplates_path %></li>
          <li><%= link_to 'Admin', rails_admin_path %></li>
        <% end %>
      <% end %>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to "Welcome #{current_user.username}", edit_user_registration_path %></li>
        <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'Login', new_user_session_path %></li>
      <% end %>
    </ul>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Exitticket</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <div class="container">
      <div class="row">
        <div class="col-md-10 col-md-offset-1 col-xl-8 col-xl-offset-2">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>